app/home/forms.py
# app/admin/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,RadioField
from wtforms.validators import DataRequired,NumberRange
from wtforms.ext.sqlalchemy.fields import QuerySelectField


class rechercherForm(FlaskForm):
    recherche = StringField('recherche', validators=[DataRequired()])
    filtre = RadioField('filtre', choices=[('0','Tous'),('1','senegal'),('2','bénin'),('3','côte d\'ivoire'),('4','Burkina fasso'),('5','Togo')])
    submit = SubmitField('Submit')

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import render_template
from flask_login import login_required
from flask import abort, render_template
from flask_login import current_user, login_required
from sqlalchemy import func



from . import home
from .forms import rechercherForm

from ..models import restaurants

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

@home.route('/recherche', methods=['GET', 'POST'])
@login_required
def recherche():
    form=rechercherForm()
    restaurant=None

    if form.validate_on_submit():
        r = form.recherche.data
        search = "%{}%".format(r)
        
        restaurant = restaurants.query.filter(restaurants.nom.like(search)).all()
        if form.filtre.data == '1':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='senegal').all()
        if form.filtre.data == '2':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='benin').all()
        if form.filtre.data == '3':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='cote-divoire').all()
        if form.filtre.data == '4':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='burkina').all()
        if form.filtre.data == '5':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='togo').all()
        
        
    """
    Render the dashboard template on the /recherche route
    """
    return render_template('home/recherche.html',form=form, restaurant=restaurant, title="Recherche")

@home.route('/recherche/<string:nom>', methods=['GET', 'POST'])
@login_required
def regarder(nom):
    # prevent non-admins from accessing the page

    r = restaurants.query.filter_by(nom=nom).first()
    form=rechercherForm()
    restaurant=None
    
    if form.validate_on_submit():
        r = form.recherche.data
        search = "%{}%".format(r)
        restaurant = restaurants.query.filter(restaurants.nom.like(search)).all()
        if form.filtre.data == '1':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='senegal').all()
        if form.filtre.data == '2':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='benin').all()
        if form.filtre.data == '3':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='cote-divoire').all()
        if form.filtre.data == '4':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='burkina').all()
        if form.filtre.data == '5':
            restaurant = restaurants.query.filter(restaurants.nom.like(search)).filter_by(pays='togo').all()
        

    return render_template('home/recherche.html', title="restaurant" ,form=form, r=r,restaurant=restaurant )

@home.route('/statistiques', methods=['GET', 'POST'])
@login_required
def donnee():
    # prevent non-admins from accessing the page
    

    Dakar = restaurants.query.filter_by(region='Dakar').count()
    Saint = restaurants.query.filter_by(region='Saint-Louis').count()
    Mbour= restaurants.query.filter_by(region="M'bour").count()
    senegal=[Dakar,Saint,Mbour]
    Abomey = restaurants.query.filter_by(region='Abomey-Calavi').count()
    Bohicon = restaurants.query.filter_by(region='Bohicon').count()
    Porto = restaurants.query.filter_by(region='Porto-Novo').count()
    Cotonou = restaurants.query.filter_by(region='Cotonou').count()
   
    benin=[Cotonou,Abomey,Bohicon,Porto]
    Grand=restaurants.query.filter_by(region='Grand-Bassam').count()
    Yamoussoukro=restaurants.query.filter_by(region='Yamoussoukro').count()
    Abidjan = restaurants.query.filter_by(region='Abidjan').count()
   
    cote=[Abidjan,Yamoussoukro,Grand]
    
    Koudougou=restaurants.query.filter_by(region='Koudougou').count()
    Bobo=restaurants.query.filter_by(region='Bobo-Dioulasso').count()
    ouagadougou=restaurants.query.filter_by(region='ouagadougou').count()
    burkina=[ouagadougou,Bobo,Koudougou]

    
    lome=restaurants.query.filter_by(region='lomé').count()
    Atakpame=restaurants.query.filter_by(region='Atakpamé').count()
    Kpalime=restaurants.query.filter_by(region='Kpalimé').count()
    togo=[lome,Atakpame,Kpalime]
    
    return render_template('home/statistique.html', title="Statistiques" ,cote=cote, senegal=senegal,benin=benin,burkina=burkina,togo=togo)


@home.route('/capitale', methods=['GET', 'POST'])
@login_required
def Max():
    Dakar = restaurants.query.filter_by(region='Dakar').count()
    Ouagadougou = restaurants.query.filter_by(region='Ouagadougou').count()
    Lome= restaurants.query.filter_by(region="lomé").count()
    Abidjan = restaurants.query.filter_by(region='Abidjan').count()
    Cotonou = restaurants.query.filter_by(region='Cotonou').count()
    nombres=[Dakar,Ouagadougou,Lome,Abidjan,Cotonou]
    return render_template('home/capitale.html', title="Statistiques" ,nombres=nombres )
    
    

app/templates/home/capitale.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}



    <!-- Bar Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Nombre de restaurants par capitale</h6>
      </div>
      <div class="card-body">
        <div class="chart-bar"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
          <canvas id="myBarChart" width="738" height="400" class="chartjs-render-monitor" style="display: block; height: 320px; width: 591px;"></canvas>
        </div>
        <hr>
      </div>
    </div>

<script src="{{ url_for('static', filename='vendor/chart.js/Chart.min.js') }}"></script>
<script >
// Set new default font family and font color to mimic Bootstrap's default styling
Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = '#858796';

function number_format(number, decimals, dec_point, thousands_sep) {
  // *     example: number_format(1234.56, 2, ',', ' ');
  // *     return: '1 234,56'
  number = (number + '').replace(',', '').replace(' ', '');
  var n = !isFinite(+number) ? 0 : +number,
    prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
    sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
    dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
    s = '',
    toFixedFix = function(n, prec) {
      var k = Math.pow(10, prec);
      return '' + Math.round(n * k) / k;
    };
  // Fix for IE parseFloat(0.55).toFixed(0) = 0;
  s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
  if (s[0].length > 3) {
    s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
  }
  if ((s[1] || '').length < prec) {
    s[1] = s[1] || '';
    s[1] += new Array(prec - s[1].length + 1).join('0');
  }
  return s.join(dec);
}

// Bar Chart Example
var ctx = document.getElementById("myBarChart");
var myBarChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: ["Dakar", "Lome", "Ouagadougou", "Cotonou", "Abidjan"],
    datasets: [{
      label: "Revenue",
      backgroundColor: "#4e73df",
      hoverBackgroundColor: "#2e59d9",
      borderColor: "#4e73df",
      data: {{nombres}},
    }],
  },
  options: {
    maintainAspectRatio: false,
    layout: {
      padding: {
        left: 10,
        right: 25,
        top: 25,
        bottom: 0
      }
    },
    scales: {
      xAxes: [{
        time: {
          unit: 'month'
        },
        gridLines: {
          display: false,
          drawBorder: false
        },
        ticks: {
          maxTicksLimit: 6
        },
        maxBarThickness: 25,
      }],
      yAxes: [{
        ticks: {
          min: 0,
          max: 600,
          maxTicksLimit: 5,
          padding: 10,
          // Include a dollar sign in the ticks
          callback: function(value, index, values) {
            return number_format(value);
          }
        },
        gridLines: {
          color: "rgb(234, 236, 244)",
          zeroLineColor: "rgb(234, 236, 244)",
          drawBorder: false,
          borderDash: [2],
          zeroLineBorderDash: [2]
        }
      }],
    },
    legend: {
      display: false
    },
    tooltips: {
      titleMarginBottom: 10,
      titleFontColor: '#6e707e',
      titleFontSize: 14,
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: '#dddfeb',
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10,
      callbacks: {
        label: function(tooltipItem, chart) {
          var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
          return datasetLabel + ': $' + number_format(tooltipItem.yLabel);
        }
      }
    },
  }
});


</script>

{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <center>               
                             <h1>Dashboard - Restaurant</h1>
                    </center>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <center>
                    <h1>Gestionnaire de restaurants</h1>
                    </center>
                    <hr >
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/recherche.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-head">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
              <div class="row">
                    <div class="col-6">
                    <div >
                        <br/>
                        {{ wtf.quick_form(form) }}

                    <hr class="intro-divider">
                </ul>   
                        
                    </div>
            </div>
            <div class="col-6">

              <div class="intro-head">
                <div class="container">
                    <div class="row">
                        <div class="card border-left-primary  border-right-primary  shadow py-2" style="width: 30rem;height:15rem;">
                               <center> <h4 class="form-inline">restaurant</h4> </center>
                                {% if r %}
                                    <div>
                                       <h3 class="">{{ r.nom }}</h3>
                                       <p >Adresse : {{ r.adresse }}</p>
                                       <p>Numero de telephone : {{ r.telephone }}</p>
                                    </div> 
                                    {% endif %}
                               
                                
                                <hr >
                                </ul>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="col-12 center">

                        {% if restaurant %}
                             <div class="col">
                            <div class="row">
                           {% for resto in restaurant %}
                                <div class="card border-left-primary shadow py-2" style="width: 15rem;height:10rem;">
                                  <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                      <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                                            <a href="{{ url_for('home.regarder', nom=resto.nom) }}"> {{ resto.nom }} </a></font></font></div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ resto.pays }}</font></font></div>
                                      </div>
                                      <div class="col-auto">
                                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                            {% endfor %}
                            
                          </div>
                        </div>
                       {% endif %}


            </div>
        </div>
        </div>
    </div>
</div>
</div>
{% endblock %}